# Alacritty Configuration File

# [window]
# # Window dimensions (changes require restart)
# dimensions = { columns = 120, lines = 30 }

# # Window padding (changes require restart)
# padding = { x = 10, y = 10 }

# # Window decorations
# decorations = "full"

# Startup Mode (changes require restart)
# startup_mode = "Windowed"

# Window opacity
# opacity = 1.0

# [scrolling]
# # Maximum number of lines in the scrollback buffer
# history = 10000
#
# # Scrolling distance multiplier
# multiplier = 3

[font]
# Normal font
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

# Bold font
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }

# Italic font
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

# Bold italic font
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

# Point size
size = 14.0

# Font Offset
offset = { x = 0, y = 0 }

# [colors]
# # Default colors
# primary = { background = "#1d1f21", foreground = "#c5c8c6" }
#
# # Cursor colors
# cursor = { text = "#1d1f21", cursor = "#ffffff" }
#
# # Selection colors
# selection = { text = "CellForeground", background = "#373b41" }
#
# # Normal colors
# normal = { black = "#1d1f21", red = "#cc6666", green = "#b5bd68", yellow = "#f0c674", blue = "#81a2be", magenta = "#b294bb", cyan = "#8abeb7", white = "#c5c8c6" }
#
# # Bright colors
# bright = { black = "#666666", red = "#d54e53", green = "#b9ca4a", yellow = "#e7c547", blue = "#7aa6da", magenta = "#c397d8", cyan = "#70c0b1", white = "#eaeaea" }

# [cursor]
# # Cursor style
# style = { shape = "Block", blinking = "Off" }
#
# # Vi mode cursor style
# vi_mode_style = { shape = "Block", blinking = "Off" }
#
# # Thickness of the cursor relative to the cell width
# thickness = 0.15

# [terminal]
# # Terminal emulator name
# osc52 = "CopyPaste"
#
# [mouse]
# # Hide cursor when typing
# hide_when_typing = true

# [selection]
# # Characters that are used as separators for "semantic words" in Alacritty
# semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"
#
# # When set to `true`, selected text will be copied to the primary clipboard
# save_to_clipboard = true
#
# [terminal.shell]
# # Shell program and its arguments
# program = "/bin/zsh"
# args = ["--login"]
#
# [keyboard]
# # Key bindings
# bindings = [
#   { key = "V", mods = "Command", action = "Paste" },
#   { key = "C", mods = "Command", action = "Copy" },
#   { key = "Q", mods = "Command", action = "Quit" },
#   { key = "N", mods = "Command", action = "SpawnNewInstance" },
#   { key = "Return", mods = "Command", action = "ToggleFullscreen" },
#   { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
#   { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
#   { key = "Key0", mods = "Command", action = "ResetFontSize" },
# ]
#
# [debug]
# # Display the time it takes to redraw each frame
# render_timer = false
#
# # Keep the log file after quitting Alacritty
# persistent_logging = false
#
# # Log level
# log_level = "Warn"
