#!/bin/bash
# This config is trying to use the same colors as Omarchy
options=(
    # style=square # Unfurtunately, square borders do not work well on mac
    style=round
    # width=2 # Omarchy uses 2 but to match a similar size we need to use 6
    width=6
    hidpi=off
    active_color="gradient(top_left=0xee33ccff,bottom_right=0xee00ff99)"
    inactive_color=0xaa595959
)
borders "${options[@]}"
