unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Config reloaded!"

# bind -T copy-mode-vi v send-keys -X begin-selection
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# forget the find window.  That is for chumps
# bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
