# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'dracula/tmux'
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @plugin 'alexwforsythe/tmux-which-key'
# set -g @plugin 'christoomey/vim-tmux-navigator'

if "test ! -d $XDG_CONFIG_HOME/tmux/plugins/tpm" \
"run 'git clone https://github.com/tmux-plugins/tpm $XDG_CONFIG_HOME/tmux/plugins/tpm && $XDG_CONFIG_HOME/tmux/plugins/tpm/bin/install_plugins'"

if "test -d $XDG_CONFIG_HOME/tmux/plugins/tpm/.git" \
"run 'rm -rf $XDG_CONFIG_HOME/tmux/plugins/tpm/.git/'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm'
