# set -g @dracula-plugins "batery git weather time"
# set -g @dracula-show-flags true
# # set -g @dracula-border-contrast true
# set -g @dracula-show-powerline true
# set -g @dracula-show-left-icon "#h | #S"
# set -g @dracula-battery-label "🗲 "
# set -g @dracula-git-disable-status false
# set -g @dracula-git-show-repo-name true
# set -g @dracula-show-timezone false
# set -g @dracula-military-time true
# set -g @dracula-show-fahrenheit false
# set -g @dracula-fixed-location "Lisbon"
# set -g @dracula-show-location false

set -g @tokyo-night-tmux_theme storm
set -g @tokyo-night-tmux_pane_id_style dsquare
set -g @tokyo-night-tmux_time_format 24H
set -g @tokyo-night-tmux_show_netspeed 0
set -g @tokyo-night-tmux_show_path 0
set -g @tokyo-night-tmux_show_battery_widget 1
